import Head from 'next/head';
import { TestNavigation } from '@/pages/TestNavigation';
import { useAccessToken } from '@/bridge/hooks/useAccessToken';


export default function Home() {
  
  const accessToken = useAccessToken();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        루트
        {accessToken && <div>accessToken: {accessToken}</div>}
        <TestNavigation />
      </div>
    </>
  );
}
